FROM node:18 as build
WORKDIR /frontend
COPY frontend/app/package*.json ./
RUN npm install
COPY frontend/app ./
RUN npm run build

FROM nginx:alpine
COPY --from=build /frontend/dist /usr/share/nginx/html
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]
